//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wellness.ClassService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Deserializer", Namespace="http://schemas.datacontract.org/2004/07/JonasFitness.ClubSolutions.CompeteDataSer" +
        "vice.ServiceConnector.DataContracts.Version2_0.Requests")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Wellness.ClassService.GetClassesRequest))]
    public partial class Deserializer : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetClassesRequest", Namespace="http://JonasFitness.com/CompeteDataService/v2_0/Requests")]
    [System.SerializableAttribute()]
    public partial class GetClassesRequest : Wellness.ClassService.Deserializer {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Wellness.ClassService.Class[] ClassesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Wellness.ClassService.Club[] ClubsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Wellness.ClassService.ClubGroup[] ClubGroupsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Wellness.ClassService.SimpleDateTimeRange StartEndDateTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime ClientDateTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Wellness.ClassService.PagingRequestInfo PageInfoField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Wellness.ClassService.Class[] Classes {
            get {
                return this.ClassesField;
            }
            set {
                if ((object.ReferenceEquals(this.ClassesField, value) != true)) {
                    this.ClassesField = value;
                    this.RaisePropertyChanged("Classes");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Wellness.ClassService.Club[] Clubs {
            get {
                return this.ClubsField;
            }
            set {
                if ((object.ReferenceEquals(this.ClubsField, value) != true)) {
                    this.ClubsField = value;
                    this.RaisePropertyChanged("Clubs");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public Wellness.ClassService.ClubGroup[] ClubGroups {
            get {
                return this.ClubGroupsField;
            }
            set {
                if ((object.ReferenceEquals(this.ClubGroupsField, value) != true)) {
                    this.ClubGroupsField = value;
                    this.RaisePropertyChanged("ClubGroups");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public Wellness.ClassService.SimpleDateTimeRange StartEndDateTime {
            get {
                return this.StartEndDateTimeField;
            }
            set {
                if ((object.ReferenceEquals(this.StartEndDateTimeField, value) != true)) {
                    this.StartEndDateTimeField = value;
                    this.RaisePropertyChanged("StartEndDateTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public System.DateTime ClientDateTime {
            get {
                return this.ClientDateTimeField;
            }
            set {
                if ((this.ClientDateTimeField.Equals(value) != true)) {
                    this.ClientDateTimeField = value;
                    this.RaisePropertyChanged("ClientDateTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public Wellness.ClassService.PagingRequestInfo PageInfo {
            get {
                return this.PageInfoField;
            }
            set {
                if ((object.ReferenceEquals(this.PageInfoField, value) != true)) {
                    this.PageInfoField = value;
                    this.RaisePropertyChanged("PageInfo");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SimpleDateTimeRange", Namespace="http://JonasFitness.com/CompeteDataService/v2_0/Common")]
    [System.SerializableAttribute()]
    public partial class SimpleDateTimeRange : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private System.DateTime StartField;
        
        private System.DateTime EndField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.DateTime Start {
            get {
                return this.StartField;
            }
            set {
                if ((this.StartField.Equals(value) != true)) {
                    this.StartField = value;
                    this.RaisePropertyChanged("Start");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public System.DateTime End {
            get {
                return this.EndField;
            }
            set {
                if ((this.EndField.Equals(value) != true)) {
                    this.EndField = value;
                    this.RaisePropertyChanged("End");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PagingRequestInfo", Namespace="http://JonasFitness.com/CompeteDataService/v2_0/Requests")]
    [System.SerializableAttribute()]
    public partial class PagingRequestInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PageSizeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Page {
            get {
                return this.PageField;
            }
            set {
                if ((this.PageField.Equals(value) != true)) {
                    this.PageField = value;
                    this.RaisePropertyChanged("Page");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PageSize {
            get {
                return this.PageSizeField;
            }
            set {
                if ((this.PageSizeField.Equals(value) != true)) {
                    this.PageSizeField = value;
                    this.RaisePropertyChanged("PageSize");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Class", Namespace="http://JonasFitness.com/CompeteDataService/v2_0/Common")]
    [System.SerializableAttribute()]
    public partial class Class : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int IDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Club", Namespace="http://JonasFitness.com/CompeteDataService/v2_0/Common")]
    [System.SerializableAttribute()]
    public partial class Club : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int IDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ClubGroup", Namespace="http://JonasFitness.com/CompeteDataService/v2_0/Common")]
    [System.SerializableAttribute()]
    public partial class ClubGroup : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int IDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResponseRoot", Namespace="http://JonasFitness.com/CompeteDataService/v2_0/Responses")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Wellness.ClassService.InsertClassesResponse))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Wellness.ClassService.InsertClassResult))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Wellness.ClassService.UpdateClassesResponse))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Wellness.ClassService.UpdateClassResult))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Wellness.ClassService.GetClassesResponse))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Wellness.ClassService.GetClassesRequest))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Wellness.ClassService.PagingRequestInfo))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Wellness.ClassService.InsertClassesRequest))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Wellness.ClassService.UpdateClassesRequest))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Wellness.ClassService.Deserializer))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Wellness.ClassService.Class[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Wellness.ClassService.Class))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Wellness.ClassService.Club[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Wellness.ClassService.Club))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Wellness.ClassService.ClubGroup[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Wellness.ClassService.ClubGroup))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Wellness.ClassService.SimpleDateTimeRange))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Wellness.ClassService.GetClassData[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Wellness.ClassService.GetClassData))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Wellness.ClassService.Employee))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Wellness.ClassService.ClassCustomer[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Wellness.ClassService.ClassCustomer))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Wellness.ClassService.Customer))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Wellness.ClassService.ClassInsert[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Wellness.ClassService.ClassInsert))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Wellness.ClassService.ClassUpdate[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Wellness.ClassService.ClassUpdate))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Wellness.ClassService.StatusInfo))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Wellness.ClassService.ErrorStatusInfo))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Wellness.ClassService.PagedResponseInfo))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Wellness.ClassService.InsertClassResult[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Wellness.ClassService.UpdateClassResult[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Wellness.ClassService.StatusCode))]
    public partial class ResponseRoot : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private object StatusInfoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public object StatusInfo {
            get {
                return this.StatusInfoField;
            }
            set {
                if ((object.ReferenceEquals(this.StatusInfoField, value) != true)) {
                    this.StatusInfoField = value;
                    this.RaisePropertyChanged("StatusInfo");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="InsertClassesResponse", Namespace="http://JonasFitness.com/CompeteDataService/v2_0/Responses")]
    [System.SerializableAttribute()]
    public partial class InsertClassesResponse : Wellness.ClassService.ResponseRoot {
        
        private Wellness.ClassService.InsertClassResult[] ResultsField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public Wellness.ClassService.InsertClassResult[] Results {
            get {
                return this.ResultsField;
            }
            set {
                if ((object.ReferenceEquals(this.ResultsField, value) != true)) {
                    this.ResultsField = value;
                    this.RaisePropertyChanged("Results");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="InsertClassResult", Namespace="http://JonasFitness.com/CompeteDataService/v2_0/Responses")]
    [System.SerializableAttribute()]
    public partial class InsertClassResult : Wellness.ClassService.ResponseRoot {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BarcodeIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ClassIDField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BarcodeID {
            get {
                return this.BarcodeIDField;
            }
            set {
                if ((object.ReferenceEquals(this.BarcodeIDField, value) != true)) {
                    this.BarcodeIDField = value;
                    this.RaisePropertyChanged("BarcodeID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ClassID {
            get {
                return this.ClassIDField;
            }
            set {
                if ((this.ClassIDField.Equals(value) != true)) {
                    this.ClassIDField = value;
                    this.RaisePropertyChanged("ClassID");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UpdateClassesResponse", Namespace="http://JonasFitness.com/CompeteDataService/v2_0/Responses")]
    [System.SerializableAttribute()]
    public partial class UpdateClassesResponse : Wellness.ClassService.ResponseRoot {
        
        private Wellness.ClassService.UpdateClassResult[] ResultsField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public Wellness.ClassService.UpdateClassResult[] Results {
            get {
                return this.ResultsField;
            }
            set {
                if ((object.ReferenceEquals(this.ResultsField, value) != true)) {
                    this.ResultsField = value;
                    this.RaisePropertyChanged("Results");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UpdateClassResult", Namespace="http://JonasFitness.com/CompeteDataService/v2_0/Responses")]
    [System.SerializableAttribute()]
    public partial class UpdateClassResult : Wellness.ClassService.ResponseRoot {
        
        private int ClassIDField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int ClassID {
            get {
                return this.ClassIDField;
            }
            set {
                if ((this.ClassIDField.Equals(value) != true)) {
                    this.ClassIDField = value;
                    this.RaisePropertyChanged("ClassID");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetClassesResponse", Namespace="http://JonasFitness.com/CompeteDataService/v2_0/Responses")]
    [System.SerializableAttribute()]
    public partial class GetClassesResponse : Wellness.ClassService.ResponseRoot {
        
        private Wellness.ClassService.GetClassData[] ClassesField;
        
        private Wellness.ClassService.PagedResponseInfo PageInfoField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public Wellness.ClassService.GetClassData[] Classes {
            get {
                return this.ClassesField;
            }
            set {
                if ((object.ReferenceEquals(this.ClassesField, value) != true)) {
                    this.ClassesField = value;
                    this.RaisePropertyChanged("Classes");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public Wellness.ClassService.PagedResponseInfo PageInfo {
            get {
                return this.PageInfoField;
            }
            set {
                if ((object.ReferenceEquals(this.PageInfoField, value) != true)) {
                    this.PageInfoField = value;
                    this.RaisePropertyChanged("PageInfo");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="InsertClassesRequest", Namespace="http://JonasFitness.com/CompeteDataService/v2_0/Requests")]
    [System.SerializableAttribute()]
    public partial class InsertClassesRequest : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private Wellness.ClassService.ClassInsert[] InsertsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public Wellness.ClassService.ClassInsert[] Inserts {
            get {
                return this.InsertsField;
            }
            set {
                if ((object.ReferenceEquals(this.InsertsField, value) != true)) {
                    this.InsertsField = value;
                    this.RaisePropertyChanged("Inserts");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UpdateClassesRequest", Namespace="http://JonasFitness.com/CompeteDataService/v2_0/Requests")]
    [System.SerializableAttribute()]
    public partial class UpdateClassesRequest : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private Wellness.ClassService.ClassUpdate[] UpdatesField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public Wellness.ClassService.ClassUpdate[] Updates {
            get {
                return this.UpdatesField;
            }
            set {
                if ((object.ReferenceEquals(this.UpdatesField, value) != true)) {
                    this.UpdatesField = value;
                    this.RaisePropertyChanged("Updates");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetClassData", Namespace="http://JonasFitness.com/CompeteDataService/v2_0/Common")]
    [System.SerializableAttribute()]
    public partial class GetClassData : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BarcodeIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Wellness.ClassService.Club ClubField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Wellness.ClassService.SimpleDateTimeRange StartEndTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Wellness.ClassService.SimpleDateTimeRange StartEndDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LongDescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Wellness.ClassService.Employee InstructorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Wellness.ClassService.Employee SubstituteInstructorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal PriceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GLCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Wellness.ClassService.Club[] SellClubsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool EnrollDailyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AvailableDaysField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CapacityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int RemainingCapacityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int EnrolledCountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int StandByCountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int AttendedCountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool ActiveField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Wellness.ClassService.ClassCustomer[] EnrolledCustomersField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Wellness.ClassService.ClassCustomer[] AttendedCustomersField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime ClassDateField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public string BarcodeID {
            get {
                return this.BarcodeIDField;
            }
            set {
                if ((object.ReferenceEquals(this.BarcodeIDField, value) != true)) {
                    this.BarcodeIDField = value;
                    this.RaisePropertyChanged("BarcodeID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public Wellness.ClassService.Club Club {
            get {
                return this.ClubField;
            }
            set {
                if ((object.ReferenceEquals(this.ClubField, value) != true)) {
                    this.ClubField = value;
                    this.RaisePropertyChanged("Club");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public Wellness.ClassService.SimpleDateTimeRange StartEndTime {
            get {
                return this.StartEndTimeField;
            }
            set {
                if ((object.ReferenceEquals(this.StartEndTimeField, value) != true)) {
                    this.StartEndTimeField = value;
                    this.RaisePropertyChanged("StartEndTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public Wellness.ClassService.SimpleDateTimeRange StartEndDate {
            get {
                return this.StartEndDateField;
            }
            set {
                if ((object.ReferenceEquals(this.StartEndDateField, value) != true)) {
                    this.StartEndDateField = value;
                    this.RaisePropertyChanged("StartEndDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=6)]
        public string LongDescription {
            get {
                return this.LongDescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.LongDescriptionField, value) != true)) {
                    this.LongDescriptionField = value;
                    this.RaisePropertyChanged("LongDescription");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=7)]
        public Wellness.ClassService.Employee Instructor {
            get {
                return this.InstructorField;
            }
            set {
                if ((object.ReferenceEquals(this.InstructorField, value) != true)) {
                    this.InstructorField = value;
                    this.RaisePropertyChanged("Instructor");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=8)]
        public Wellness.ClassService.Employee SubstituteInstructor {
            get {
                return this.SubstituteInstructorField;
            }
            set {
                if ((object.ReferenceEquals(this.SubstituteInstructorField, value) != true)) {
                    this.SubstituteInstructorField = value;
                    this.RaisePropertyChanged("SubstituteInstructor");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=9)]
        public decimal Price {
            get {
                return this.PriceField;
            }
            set {
                if ((this.PriceField.Equals(value) != true)) {
                    this.PriceField = value;
                    this.RaisePropertyChanged("Price");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=10)]
        public string GLCode {
            get {
                return this.GLCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.GLCodeField, value) != true)) {
                    this.GLCodeField = value;
                    this.RaisePropertyChanged("GLCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=11)]
        public Wellness.ClassService.Club[] SellClubs {
            get {
                return this.SellClubsField;
            }
            set {
                if ((object.ReferenceEquals(this.SellClubsField, value) != true)) {
                    this.SellClubsField = value;
                    this.RaisePropertyChanged("SellClubs");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=12)]
        public bool EnrollDaily {
            get {
                return this.EnrollDailyField;
            }
            set {
                if ((this.EnrollDailyField.Equals(value) != true)) {
                    this.EnrollDailyField = value;
                    this.RaisePropertyChanged("EnrollDaily");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=13)]
        public string AvailableDays {
            get {
                return this.AvailableDaysField;
            }
            set {
                if ((object.ReferenceEquals(this.AvailableDaysField, value) != true)) {
                    this.AvailableDaysField = value;
                    this.RaisePropertyChanged("AvailableDays");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=14)]
        public int Capacity {
            get {
                return this.CapacityField;
            }
            set {
                if ((this.CapacityField.Equals(value) != true)) {
                    this.CapacityField = value;
                    this.RaisePropertyChanged("Capacity");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=15)]
        public int RemainingCapacity {
            get {
                return this.RemainingCapacityField;
            }
            set {
                if ((this.RemainingCapacityField.Equals(value) != true)) {
                    this.RemainingCapacityField = value;
                    this.RaisePropertyChanged("RemainingCapacity");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=16)]
        public int EnrolledCount {
            get {
                return this.EnrolledCountField;
            }
            set {
                if ((this.EnrolledCountField.Equals(value) != true)) {
                    this.EnrolledCountField = value;
                    this.RaisePropertyChanged("EnrolledCount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=17)]
        public int StandByCount {
            get {
                return this.StandByCountField;
            }
            set {
                if ((this.StandByCountField.Equals(value) != true)) {
                    this.StandByCountField = value;
                    this.RaisePropertyChanged("StandByCount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=18)]
        public int AttendedCount {
            get {
                return this.AttendedCountField;
            }
            set {
                if ((this.AttendedCountField.Equals(value) != true)) {
                    this.AttendedCountField = value;
                    this.RaisePropertyChanged("AttendedCount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=19)]
        public bool Active {
            get {
                return this.ActiveField;
            }
            set {
                if ((this.ActiveField.Equals(value) != true)) {
                    this.ActiveField = value;
                    this.RaisePropertyChanged("Active");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=20)]
        public Wellness.ClassService.ClassCustomer[] EnrolledCustomers {
            get {
                return this.EnrolledCustomersField;
            }
            set {
                if ((object.ReferenceEquals(this.EnrolledCustomersField, value) != true)) {
                    this.EnrolledCustomersField = value;
                    this.RaisePropertyChanged("EnrolledCustomers");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=21)]
        public Wellness.ClassService.ClassCustomer[] AttendedCustomers {
            get {
                return this.AttendedCustomersField;
            }
            set {
                if ((object.ReferenceEquals(this.AttendedCustomersField, value) != true)) {
                    this.AttendedCustomersField = value;
                    this.RaisePropertyChanged("AttendedCustomers");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=22)]
        public System.DateTime ClassDate {
            get {
                return this.ClassDateField;
            }
            set {
                if ((this.ClassDateField.Equals(value) != true)) {
                    this.ClassDateField = value;
                    this.RaisePropertyChanged("ClassDate");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Employee", Namespace="http://JonasFitness.com/CompeteDataService/v2_0/Common")]
    [System.SerializableAttribute()]
    public partial class Employee : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ClassCustomer", Namespace="http://JonasFitness.com/CompeteDataService/v2_0/Common")]
    [System.SerializableAttribute()]
    public partial class ClassCustomer : Wellness.ClassService.Customer {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime ActionDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int EnrollmentStatusField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime ActionDate {
            get {
                return this.ActionDateField;
            }
            set {
                if ((this.ActionDateField.Equals(value) != true)) {
                    this.ActionDateField = value;
                    this.RaisePropertyChanged("ActionDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int EnrollmentStatus {
            get {
                return this.EnrollmentStatusField;
            }
            set {
                if ((this.EnrollmentStatusField.Equals(value) != true)) {
                    this.EnrollmentStatusField = value;
                    this.RaisePropertyChanged("EnrollmentStatus");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Customer", Namespace="http://JonasFitness.com/CompeteDataService/v2_0/Common")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Wellness.ClassService.ClassCustomer))]
    public partial class Customer : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int IDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ClassInsert", Namespace="http://JonasFitness.com/CompeteDataService/v2_0/Common")]
    [System.SerializableAttribute()]
    public partial class ClassInsert : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string BarcodeIDField;
        
        private string DescriptionField;
        
        private Wellness.ClassService.Club ClubField;
        
        private Wellness.ClassService.SimpleDateTimeRange StartEndTimeField;
        
        private Wellness.ClassService.SimpleDateTimeRange StartEndDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LongDescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Wellness.ClassService.Employee InstructorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal PriceField;
        
        private string GLCodeField;
        
        private Wellness.ClassService.Club[] SellClubsField;
        
        private bool EnrollDailyField;
        
        private string AvailableDaysField;
        
        private int CapacityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool ActiveField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string BarcodeID {
            get {
                return this.BarcodeIDField;
            }
            set {
                if ((object.ReferenceEquals(this.BarcodeIDField, value) != true)) {
                    this.BarcodeIDField = value;
                    this.RaisePropertyChanged("BarcodeID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public Wellness.ClassService.Club Club {
            get {
                return this.ClubField;
            }
            set {
                if ((object.ReferenceEquals(this.ClubField, value) != true)) {
                    this.ClubField = value;
                    this.RaisePropertyChanged("Club");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public Wellness.ClassService.SimpleDateTimeRange StartEndTime {
            get {
                return this.StartEndTimeField;
            }
            set {
                if ((object.ReferenceEquals(this.StartEndTimeField, value) != true)) {
                    this.StartEndTimeField = value;
                    this.RaisePropertyChanged("StartEndTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public Wellness.ClassService.SimpleDateTimeRange StartEndDate {
            get {
                return this.StartEndDateField;
            }
            set {
                if ((object.ReferenceEquals(this.StartEndDateField, value) != true)) {
                    this.StartEndDateField = value;
                    this.RaisePropertyChanged("StartEndDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public string LongDescription {
            get {
                return this.LongDescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.LongDescriptionField, value) != true)) {
                    this.LongDescriptionField = value;
                    this.RaisePropertyChanged("LongDescription");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=6)]
        public Wellness.ClassService.Employee Instructor {
            get {
                return this.InstructorField;
            }
            set {
                if ((object.ReferenceEquals(this.InstructorField, value) != true)) {
                    this.InstructorField = value;
                    this.RaisePropertyChanged("Instructor");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=7)]
        public decimal Price {
            get {
                return this.PriceField;
            }
            set {
                if ((this.PriceField.Equals(value) != true)) {
                    this.PriceField = value;
                    this.RaisePropertyChanged("Price");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=8)]
        public string GLCode {
            get {
                return this.GLCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.GLCodeField, value) != true)) {
                    this.GLCodeField = value;
                    this.RaisePropertyChanged("GLCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=9)]
        public Wellness.ClassService.Club[] SellClubs {
            get {
                return this.SellClubsField;
            }
            set {
                if ((object.ReferenceEquals(this.SellClubsField, value) != true)) {
                    this.SellClubsField = value;
                    this.RaisePropertyChanged("SellClubs");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=10)]
        public bool EnrollDaily {
            get {
                return this.EnrollDailyField;
            }
            set {
                if ((this.EnrollDailyField.Equals(value) != true)) {
                    this.EnrollDailyField = value;
                    this.RaisePropertyChanged("EnrollDaily");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=11)]
        public string AvailableDays {
            get {
                return this.AvailableDaysField;
            }
            set {
                if ((object.ReferenceEquals(this.AvailableDaysField, value) != true)) {
                    this.AvailableDaysField = value;
                    this.RaisePropertyChanged("AvailableDays");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=12)]
        public int Capacity {
            get {
                return this.CapacityField;
            }
            set {
                if ((this.CapacityField.Equals(value) != true)) {
                    this.CapacityField = value;
                    this.RaisePropertyChanged("Capacity");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=13)]
        public bool Active {
            get {
                return this.ActiveField;
            }
            set {
                if ((this.ActiveField.Equals(value) != true)) {
                    this.ActiveField = value;
                    this.RaisePropertyChanged("Active");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ClassUpdate", Namespace="http://JonasFitness.com/CompeteDataService/v2_0/Common")]
    [System.SerializableAttribute()]
    public partial class ClassUpdate : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BarcodeIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Wellness.ClassService.Club ClubField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Wellness.ClassService.SimpleDateTimeRange StartEndTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Wellness.ClassService.SimpleDateTimeRange StartEndDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LongDescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Wellness.ClassService.Employee InstructorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> PriceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GLCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Wellness.ClassService.Club[] SellClubsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<bool> EnrollDailyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AvailableDaysField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> CapacityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<bool> ActiveField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public string BarcodeID {
            get {
                return this.BarcodeIDField;
            }
            set {
                if ((object.ReferenceEquals(this.BarcodeIDField, value) != true)) {
                    this.BarcodeIDField = value;
                    this.RaisePropertyChanged("BarcodeID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public Wellness.ClassService.Club Club {
            get {
                return this.ClubField;
            }
            set {
                if ((object.ReferenceEquals(this.ClubField, value) != true)) {
                    this.ClubField = value;
                    this.RaisePropertyChanged("Club");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public Wellness.ClassService.SimpleDateTimeRange StartEndTime {
            get {
                return this.StartEndTimeField;
            }
            set {
                if ((object.ReferenceEquals(this.StartEndTimeField, value) != true)) {
                    this.StartEndTimeField = value;
                    this.RaisePropertyChanged("StartEndTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public Wellness.ClassService.SimpleDateTimeRange StartEndDate {
            get {
                return this.StartEndDateField;
            }
            set {
                if ((object.ReferenceEquals(this.StartEndDateField, value) != true)) {
                    this.StartEndDateField = value;
                    this.RaisePropertyChanged("StartEndDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=6)]
        public string LongDescription {
            get {
                return this.LongDescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.LongDescriptionField, value) != true)) {
                    this.LongDescriptionField = value;
                    this.RaisePropertyChanged("LongDescription");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=7)]
        public Wellness.ClassService.Employee Instructor {
            get {
                return this.InstructorField;
            }
            set {
                if ((object.ReferenceEquals(this.InstructorField, value) != true)) {
                    this.InstructorField = value;
                    this.RaisePropertyChanged("Instructor");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=8)]
        public System.Nullable<decimal> Price {
            get {
                return this.PriceField;
            }
            set {
                if ((this.PriceField.Equals(value) != true)) {
                    this.PriceField = value;
                    this.RaisePropertyChanged("Price");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=9)]
        public string GLCode {
            get {
                return this.GLCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.GLCodeField, value) != true)) {
                    this.GLCodeField = value;
                    this.RaisePropertyChanged("GLCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=10)]
        public Wellness.ClassService.Club[] SellClubs {
            get {
                return this.SellClubsField;
            }
            set {
                if ((object.ReferenceEquals(this.SellClubsField, value) != true)) {
                    this.SellClubsField = value;
                    this.RaisePropertyChanged("SellClubs");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=11)]
        public System.Nullable<bool> EnrollDaily {
            get {
                return this.EnrollDailyField;
            }
            set {
                if ((this.EnrollDailyField.Equals(value) != true)) {
                    this.EnrollDailyField = value;
                    this.RaisePropertyChanged("EnrollDaily");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=12)]
        public string AvailableDays {
            get {
                return this.AvailableDaysField;
            }
            set {
                if ((object.ReferenceEquals(this.AvailableDaysField, value) != true)) {
                    this.AvailableDaysField = value;
                    this.RaisePropertyChanged("AvailableDays");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=13)]
        public System.Nullable<int> Capacity {
            get {
                return this.CapacityField;
            }
            set {
                if ((this.CapacityField.Equals(value) != true)) {
                    this.CapacityField = value;
                    this.RaisePropertyChanged("Capacity");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=14)]
        public System.Nullable<bool> Active {
            get {
                return this.ActiveField;
            }
            set {
                if ((this.ActiveField.Equals(value) != true)) {
                    this.ActiveField = value;
                    this.RaisePropertyChanged("Active");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="StatusInfo", Namespace="http://JonasFitness.com/CompeteDataService/v2_0/Responses")]
    [System.SerializableAttribute()]
    public partial class StatusInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private Wellness.ClassService.StatusCode StatusField;
        
        private string MessageField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public Wellness.ClassService.StatusCode Status {
            get {
                return this.StatusField;
            }
            set {
                if ((this.StatusField.Equals(value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ErrorStatusInfo", Namespace="http://JonasFitness.com/CompeteDataService/v2_0/Responses")]
    [System.SerializableAttribute()]
    public partial class ErrorStatusInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private Wellness.ClassService.StatusCode StatusField;
        
        private string MessageField;
        
        private int ErrorNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RequestEchoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public Wellness.ClassService.StatusCode Status {
            get {
                return this.StatusField;
            }
            set {
                if ((this.StatusField.Equals(value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public int ErrorNumber {
            get {
                return this.ErrorNumberField;
            }
            set {
                if ((this.ErrorNumberField.Equals(value) != true)) {
                    this.ErrorNumberField = value;
                    this.RaisePropertyChanged("ErrorNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public string RequestEcho {
            get {
                return this.RequestEchoField;
            }
            set {
                if ((object.ReferenceEquals(this.RequestEchoField, value) != true)) {
                    this.RequestEchoField = value;
                    this.RaisePropertyChanged("RequestEcho");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PagedResponseInfo", Namespace="http://JonasFitness.com/CompeteDataService/v2_0/Responses")]
    [System.SerializableAttribute()]
    public partial class PagedResponseInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int PageField;
        
        private int PageSizeField;
        
        private int TotalPagesField;
        
        private int TotalRecordsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Page {
            get {
                return this.PageField;
            }
            set {
                if ((this.PageField.Equals(value) != true)) {
                    this.PageField = value;
                    this.RaisePropertyChanged("Page");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int PageSize {
            get {
                return this.PageSizeField;
            }
            set {
                if ((this.PageSizeField.Equals(value) != true)) {
                    this.PageSizeField = value;
                    this.RaisePropertyChanged("PageSize");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int TotalPages {
            get {
                return this.TotalPagesField;
            }
            set {
                if ((this.TotalPagesField.Equals(value) != true)) {
                    this.TotalPagesField = value;
                    this.RaisePropertyChanged("TotalPages");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int TotalRecords {
            get {
                return this.TotalRecordsField;
            }
            set {
                if ((this.TotalRecordsField.Equals(value) != true)) {
                    this.TotalRecordsField = value;
                    this.RaisePropertyChanged("TotalRecords");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="StatusCode", Namespace="http://schemas.datacontract.org/2004/07/JonasFitness.ClubSolutions.CompeteDataSer" +
        "vice.ServiceConnector.DataContracts.Version2_0.Responses")]
    public enum StatusCode : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Success = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Warning = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SystemError = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        RequestError = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        AuthenticationError = 4,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://JonasFitness.com/CompeteDataService/v2_0/ClassService", ConfigurationName="ClassService.IClassService")]
    public interface IClassService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://JonasFitness.com/CompeteDataService/v2_0/ClassService/GetClasses", ReplyAction="http://JonasFitness.com/CompeteDataService/v2_0/ClassService/IClassService/GetCla" +
            "ssesResponse")]
        Wellness.ClassService.GetClassesResponse GetClasses(Wellness.ClassService.GetClassesRequest GetClassesRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://JonasFitness.com/CompeteDataService/v2_0/ClassService/GetClasses", ReplyAction="http://JonasFitness.com/CompeteDataService/v2_0/ClassService/IClassService/GetCla" +
            "ssesResponse")]
        System.Threading.Tasks.Task<Wellness.ClassService.GetClassesResponse> GetClassesAsync(Wellness.ClassService.GetClassesRequest GetClassesRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://JonasFitness.com/CompeteDataService/v2_0/ClassService/InsertClasses", ReplyAction="http://JonasFitness.com/CompeteDataService/v2_0/ClassService/IClassService/Insert" +
            "ClassesResponse")]
        Wellness.ClassService.InsertClassesResponse InsertClasses(Wellness.ClassService.InsertClassesRequest InsertClassesRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://JonasFitness.com/CompeteDataService/v2_0/ClassService/InsertClasses", ReplyAction="http://JonasFitness.com/CompeteDataService/v2_0/ClassService/IClassService/Insert" +
            "ClassesResponse")]
        System.Threading.Tasks.Task<Wellness.ClassService.InsertClassesResponse> InsertClassesAsync(Wellness.ClassService.InsertClassesRequest InsertClassesRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://JonasFitness.com/CompeteDataService/v2_0/ClassService/UpdateClasses", ReplyAction="http://JonasFitness.com/CompeteDataService/v2_0/ClassService/IClassService/Update" +
            "ClassesResponse")]
        Wellness.ClassService.UpdateClassesResponse UpdateClasses(Wellness.ClassService.UpdateClassesRequest UpdateClassesRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://JonasFitness.com/CompeteDataService/v2_0/ClassService/UpdateClasses", ReplyAction="http://JonasFitness.com/CompeteDataService/v2_0/ClassService/IClassService/Update" +
            "ClassesResponse")]
        System.Threading.Tasks.Task<Wellness.ClassService.UpdateClassesResponse> UpdateClassesAsync(Wellness.ClassService.UpdateClassesRequest UpdateClassesRequest);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IClassServiceChannel : Wellness.ClassService.IClassService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ClassServiceClient : System.ServiceModel.ClientBase<Wellness.ClassService.IClassService>, Wellness.ClassService.IClassService {
        
        public ClassServiceClient() {
        }
        
        public ClassServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ClassServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ClassServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ClassServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Wellness.ClassService.GetClassesResponse GetClasses(Wellness.ClassService.GetClassesRequest GetClassesRequest) {
            return base.Channel.GetClasses(GetClassesRequest);
        }
        
        public System.Threading.Tasks.Task<Wellness.ClassService.GetClassesResponse> GetClassesAsync(Wellness.ClassService.GetClassesRequest GetClassesRequest) {
            return base.Channel.GetClassesAsync(GetClassesRequest);
        }
        
        public Wellness.ClassService.InsertClassesResponse InsertClasses(Wellness.ClassService.InsertClassesRequest InsertClassesRequest) {
            return base.Channel.InsertClasses(InsertClassesRequest);
        }
        
        public System.Threading.Tasks.Task<Wellness.ClassService.InsertClassesResponse> InsertClassesAsync(Wellness.ClassService.InsertClassesRequest InsertClassesRequest) {
            return base.Channel.InsertClassesAsync(InsertClassesRequest);
        }
        
        public Wellness.ClassService.UpdateClassesResponse UpdateClasses(Wellness.ClassService.UpdateClassesRequest UpdateClassesRequest) {
            return base.Channel.UpdateClasses(UpdateClassesRequest);
        }
        
        public System.Threading.Tasks.Task<Wellness.ClassService.UpdateClassesResponse> UpdateClassesAsync(Wellness.ClassService.UpdateClassesRequest UpdateClassesRequest) {
            return base.Channel.UpdateClassesAsync(UpdateClassesRequest);
        }
    }
}
