//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wellness.EmployeeService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Deserializer", Namespace="http://schemas.datacontract.org/2004/07/JonasFitness.ClubSolutions.CompeteDataSer" +
        "vice.ServiceConnector.DataContracts.Version2_0.Requests")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Wellness.EmployeeService.GetEmployeesRequest))]
    public partial class Deserializer : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetEmployeesRequest", Namespace="http://JonasFitness.com/CompeteDataService/v2_0/Requests")]
    [System.SerializableAttribute()]
    public partial class GetEmployeesRequest : Wellness.EmployeeService.Deserializer {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Wellness.EmployeeService.Club[] ClubsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Wellness.EmployeeService.Employee[] EmployeesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Wellness.EmployeeService.ClubGroup[] ClubGroupsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Wellness.EmployeeService.PagingRequestInfo PageInfoField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Wellness.EmployeeService.Club[] Clubs {
            get {
                return this.ClubsField;
            }
            set {
                if ((object.ReferenceEquals(this.ClubsField, value) != true)) {
                    this.ClubsField = value;
                    this.RaisePropertyChanged("Clubs");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Wellness.EmployeeService.Employee[] Employees {
            get {
                return this.EmployeesField;
            }
            set {
                if ((object.ReferenceEquals(this.EmployeesField, value) != true)) {
                    this.EmployeesField = value;
                    this.RaisePropertyChanged("Employees");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public Wellness.EmployeeService.ClubGroup[] ClubGroups {
            get {
                return this.ClubGroupsField;
            }
            set {
                if ((object.ReferenceEquals(this.ClubGroupsField, value) != true)) {
                    this.ClubGroupsField = value;
                    this.RaisePropertyChanged("ClubGroups");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public Wellness.EmployeeService.PagingRequestInfo PageInfo {
            get {
                return this.PageInfoField;
            }
            set {
                if ((object.ReferenceEquals(this.PageInfoField, value) != true)) {
                    this.PageInfoField = value;
                    this.RaisePropertyChanged("PageInfo");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PagingRequestInfo", Namespace="http://JonasFitness.com/CompeteDataService/v2_0/Requests")]
    [System.SerializableAttribute()]
    public partial class PagingRequestInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PageSizeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Page {
            get {
                return this.PageField;
            }
            set {
                if ((this.PageField.Equals(value) != true)) {
                    this.PageField = value;
                    this.RaisePropertyChanged("Page");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PageSize {
            get {
                return this.PageSizeField;
            }
            set {
                if ((this.PageSizeField.Equals(value) != true)) {
                    this.PageSizeField = value;
                    this.RaisePropertyChanged("PageSize");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Club", Namespace="http://JonasFitness.com/CompeteDataService/v2_0/Common")]
    [System.SerializableAttribute()]
    public partial class Club : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int IDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Employee", Namespace="http://JonasFitness.com/CompeteDataService/v2_0/Common")]
    [System.SerializableAttribute()]
    public partial class Employee : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ClubGroup", Namespace="http://JonasFitness.com/CompeteDataService/v2_0/Common")]
    [System.SerializableAttribute()]
    public partial class ClubGroup : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int IDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResponseRoot", Namespace="http://JonasFitness.com/CompeteDataService/v2_0/Responses")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Wellness.EmployeeService.InsertEmployeesResponse))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Wellness.EmployeeService.InsertEmployeeResult))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Wellness.EmployeeService.UpdateEmployeesResponse))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Wellness.EmployeeService.UpdateEmployeeResult))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Wellness.EmployeeService.GetEmployeesResponse))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Wellness.EmployeeService.GetEmployeesRequest))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Wellness.EmployeeService.PagingRequestInfo))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Wellness.EmployeeService.InsertEmployeesRequest))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Wellness.EmployeeService.UpdateEmployeesRequest))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Wellness.EmployeeService.Deserializer))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Wellness.EmployeeService.Club[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Wellness.EmployeeService.Club))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Wellness.EmployeeService.Employee[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Wellness.EmployeeService.Employee))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Wellness.EmployeeService.ClubGroup[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Wellness.EmployeeService.ClubGroup))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Wellness.EmployeeService.DetailedEmployee[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Wellness.EmployeeService.DetailedEmployee))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Wellness.EmployeeService.EmployeeInsert[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Wellness.EmployeeService.EmployeeInsert))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Wellness.EmployeeService.EmployeeUpdate[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Wellness.EmployeeService.EmployeeUpdate))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Wellness.EmployeeService.StatusInfo))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Wellness.EmployeeService.ErrorStatusInfo))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Wellness.EmployeeService.PagedResponseInfo))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Wellness.EmployeeService.InsertEmployeeResult[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Wellness.EmployeeService.UpdateEmployeeResult[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Wellness.EmployeeService.StatusCode))]
    public partial class ResponseRoot : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private object StatusInfoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public object StatusInfo {
            get {
                return this.StatusInfoField;
            }
            set {
                if ((object.ReferenceEquals(this.StatusInfoField, value) != true)) {
                    this.StatusInfoField = value;
                    this.RaisePropertyChanged("StatusInfo");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="InsertEmployeesResponse", Namespace="http://JonasFitness.com/CompeteDataService/v2_0/Responses")]
    [System.SerializableAttribute()]
    public partial class InsertEmployeesResponse : Wellness.EmployeeService.ResponseRoot {
        
        private Wellness.EmployeeService.InsertEmployeeResult[] ResultsField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public Wellness.EmployeeService.InsertEmployeeResult[] Results {
            get {
                return this.ResultsField;
            }
            set {
                if ((object.ReferenceEquals(this.ResultsField, value) != true)) {
                    this.ResultsField = value;
                    this.RaisePropertyChanged("Results");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="InsertEmployeeResult", Namespace="http://JonasFitness.com/CompeteDataService/v2_0/Responses")]
    [System.SerializableAttribute()]
    public partial class InsertEmployeeResult : Wellness.EmployeeService.ResponseRoot {
        
        private string BarcodeIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int EmployeeIDField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string BarcodeID {
            get {
                return this.BarcodeIDField;
            }
            set {
                if ((object.ReferenceEquals(this.BarcodeIDField, value) != true)) {
                    this.BarcodeIDField = value;
                    this.RaisePropertyChanged("BarcodeID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int EmployeeID {
            get {
                return this.EmployeeIDField;
            }
            set {
                if ((this.EmployeeIDField.Equals(value) != true)) {
                    this.EmployeeIDField = value;
                    this.RaisePropertyChanged("EmployeeID");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UpdateEmployeesResponse", Namespace="http://JonasFitness.com/CompeteDataService/v2_0/Responses")]
    [System.SerializableAttribute()]
    public partial class UpdateEmployeesResponse : Wellness.EmployeeService.ResponseRoot {
        
        private Wellness.EmployeeService.UpdateEmployeeResult[] ResultsField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public Wellness.EmployeeService.UpdateEmployeeResult[] Results {
            get {
                return this.ResultsField;
            }
            set {
                if ((object.ReferenceEquals(this.ResultsField, value) != true)) {
                    this.ResultsField = value;
                    this.RaisePropertyChanged("Results");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UpdateEmployeeResult", Namespace="http://JonasFitness.com/CompeteDataService/v2_0/Responses")]
    [System.SerializableAttribute()]
    public partial class UpdateEmployeeResult : Wellness.EmployeeService.ResponseRoot {
        
        private int EmployeeIDField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int EmployeeID {
            get {
                return this.EmployeeIDField;
            }
            set {
                if ((this.EmployeeIDField.Equals(value) != true)) {
                    this.EmployeeIDField = value;
                    this.RaisePropertyChanged("EmployeeID");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetEmployeesResponse", Namespace="http://JonasFitness.com/CompeteDataService/v2_0/Responses")]
    [System.SerializableAttribute()]
    public partial class GetEmployeesResponse : Wellness.EmployeeService.ResponseRoot {
        
        private Wellness.EmployeeService.DetailedEmployee[] EmployeesField;
        
        private Wellness.EmployeeService.PagedResponseInfo PageInfoField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public Wellness.EmployeeService.DetailedEmployee[] Employees {
            get {
                return this.EmployeesField;
            }
            set {
                if ((object.ReferenceEquals(this.EmployeesField, value) != true)) {
                    this.EmployeesField = value;
                    this.RaisePropertyChanged("Employees");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public Wellness.EmployeeService.PagedResponseInfo PageInfo {
            get {
                return this.PageInfoField;
            }
            set {
                if ((object.ReferenceEquals(this.PageInfoField, value) != true)) {
                    this.PageInfoField = value;
                    this.RaisePropertyChanged("PageInfo");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="InsertEmployeesRequest", Namespace="http://JonasFitness.com/CompeteDataService/v2_0/Requests")]
    [System.SerializableAttribute()]
    public partial class InsertEmployeesRequest : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private Wellness.EmployeeService.EmployeeInsert[] InsertsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public Wellness.EmployeeService.EmployeeInsert[] Inserts {
            get {
                return this.InsertsField;
            }
            set {
                if ((object.ReferenceEquals(this.InsertsField, value) != true)) {
                    this.InsertsField = value;
                    this.RaisePropertyChanged("Inserts");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UpdateEmployeesRequest", Namespace="http://JonasFitness.com/CompeteDataService/v2_0/Requests")]
    [System.SerializableAttribute()]
    public partial class UpdateEmployeesRequest : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private Wellness.EmployeeService.EmployeeUpdate[] UpdatesField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public Wellness.EmployeeService.EmployeeUpdate[] Updates {
            get {
                return this.UpdatesField;
            }
            set {
                if ((object.ReferenceEquals(this.UpdatesField, value) != true)) {
                    this.UpdatesField = value;
                    this.RaisePropertyChanged("Updates");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DetailedEmployee", Namespace="http://JonasFitness.com/CompeteDataService/v2_0/Common")]
    [System.SerializableAttribute()]
    public partial class DetailedEmployee : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<bool> ActiveField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Address1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Address2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BarcodeIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Wellness.EmployeeService.Club ClubField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Wellness.EmployeeService.Club[] ClubAccessField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> DateOfBirthField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmergencyContactField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmergencyPhoneField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FirstNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string HomePhoneField;
        
        private int IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Wellness.EmployeeService.Club[] InstructorSearchClubsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LastNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MiddleInitialField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MobilePhoneField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PreferredNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ZipCodeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> Active {
            get {
                return this.ActiveField;
            }
            set {
                if ((this.ActiveField.Equals(value) != true)) {
                    this.ActiveField = value;
                    this.RaisePropertyChanged("Active");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Address1 {
            get {
                return this.Address1Field;
            }
            set {
                if ((object.ReferenceEquals(this.Address1Field, value) != true)) {
                    this.Address1Field = value;
                    this.RaisePropertyChanged("Address1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Address2 {
            get {
                return this.Address2Field;
            }
            set {
                if ((object.ReferenceEquals(this.Address2Field, value) != true)) {
                    this.Address2Field = value;
                    this.RaisePropertyChanged("Address2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BarcodeID {
            get {
                return this.BarcodeIDField;
            }
            set {
                if ((object.ReferenceEquals(this.BarcodeIDField, value) != true)) {
                    this.BarcodeIDField = value;
                    this.RaisePropertyChanged("BarcodeID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string City {
            get {
                return this.CityField;
            }
            set {
                if ((object.ReferenceEquals(this.CityField, value) != true)) {
                    this.CityField = value;
                    this.RaisePropertyChanged("City");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Wellness.EmployeeService.Club Club {
            get {
                return this.ClubField;
            }
            set {
                if ((object.ReferenceEquals(this.ClubField, value) != true)) {
                    this.ClubField = value;
                    this.RaisePropertyChanged("Club");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Wellness.EmployeeService.Club[] ClubAccess {
            get {
                return this.ClubAccessField;
            }
            set {
                if ((object.ReferenceEquals(this.ClubAccessField, value) != true)) {
                    this.ClubAccessField = value;
                    this.RaisePropertyChanged("ClubAccess");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> DateOfBirth {
            get {
                return this.DateOfBirthField;
            }
            set {
                if ((this.DateOfBirthField.Equals(value) != true)) {
                    this.DateOfBirthField = value;
                    this.RaisePropertyChanged("DateOfBirth");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EmergencyContact {
            get {
                return this.EmergencyContactField;
            }
            set {
                if ((object.ReferenceEquals(this.EmergencyContactField, value) != true)) {
                    this.EmergencyContactField = value;
                    this.RaisePropertyChanged("EmergencyContact");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EmergencyPhone {
            get {
                return this.EmergencyPhoneField;
            }
            set {
                if ((object.ReferenceEquals(this.EmergencyPhoneField, value) != true)) {
                    this.EmergencyPhoneField = value;
                    this.RaisePropertyChanged("EmergencyPhone");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FirstName {
            get {
                return this.FirstNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FirstNameField, value) != true)) {
                    this.FirstNameField = value;
                    this.RaisePropertyChanged("FirstName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string HomePhone {
            get {
                return this.HomePhoneField;
            }
            set {
                if ((object.ReferenceEquals(this.HomePhoneField, value) != true)) {
                    this.HomePhoneField = value;
                    this.RaisePropertyChanged("HomePhone");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Wellness.EmployeeService.Club[] InstructorSearchClubs {
            get {
                return this.InstructorSearchClubsField;
            }
            set {
                if ((object.ReferenceEquals(this.InstructorSearchClubsField, value) != true)) {
                    this.InstructorSearchClubsField = value;
                    this.RaisePropertyChanged("InstructorSearchClubs");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LastName {
            get {
                return this.LastNameField;
            }
            set {
                if ((object.ReferenceEquals(this.LastNameField, value) != true)) {
                    this.LastNameField = value;
                    this.RaisePropertyChanged("LastName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MiddleInitial {
            get {
                return this.MiddleInitialField;
            }
            set {
                if ((object.ReferenceEquals(this.MiddleInitialField, value) != true)) {
                    this.MiddleInitialField = value;
                    this.RaisePropertyChanged("MiddleInitial");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MobilePhone {
            get {
                return this.MobilePhoneField;
            }
            set {
                if ((object.ReferenceEquals(this.MobilePhoneField, value) != true)) {
                    this.MobilePhoneField = value;
                    this.RaisePropertyChanged("MobilePhone");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PreferredName {
            get {
                return this.PreferredNameField;
            }
            set {
                if ((object.ReferenceEquals(this.PreferredNameField, value) != true)) {
                    this.PreferredNameField = value;
                    this.RaisePropertyChanged("PreferredName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string State {
            get {
                return this.StateField;
            }
            set {
                if ((object.ReferenceEquals(this.StateField, value) != true)) {
                    this.StateField = value;
                    this.RaisePropertyChanged("State");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ZipCode {
            get {
                return this.ZipCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.ZipCodeField, value) != true)) {
                    this.ZipCodeField = value;
                    this.RaisePropertyChanged("ZipCode");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EmployeeInsert", Namespace="http://JonasFitness.com/CompeteDataService/v2_0/Common")]
    [System.SerializableAttribute()]
    public partial class EmployeeInsert : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<bool> ActiveField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Address1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Address2Field;
        
        private string BarcodeIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Wellness.EmployeeService.Club ClubField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Wellness.EmployeeService.Club[] ClubAccessField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> DateOfBirthField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmergencyContactField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmergencyPhoneField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FirstNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string HomePhoneField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Wellness.EmployeeService.ClubGroup[] InstructorSearchClubGroupsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Wellness.EmployeeService.Club[] InstructorSearchClubsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LastNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MiddleInitialField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MobilePhoneField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PreferredNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ZipCodeField;
        
        private string PasswordField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> Active {
            get {
                return this.ActiveField;
            }
            set {
                if ((this.ActiveField.Equals(value) != true)) {
                    this.ActiveField = value;
                    this.RaisePropertyChanged("Active");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Address1 {
            get {
                return this.Address1Field;
            }
            set {
                if ((object.ReferenceEquals(this.Address1Field, value) != true)) {
                    this.Address1Field = value;
                    this.RaisePropertyChanged("Address1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Address2 {
            get {
                return this.Address2Field;
            }
            set {
                if ((object.ReferenceEquals(this.Address2Field, value) != true)) {
                    this.Address2Field = value;
                    this.RaisePropertyChanged("Address2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string BarcodeID {
            get {
                return this.BarcodeIDField;
            }
            set {
                if ((object.ReferenceEquals(this.BarcodeIDField, value) != true)) {
                    this.BarcodeIDField = value;
                    this.RaisePropertyChanged("BarcodeID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string City {
            get {
                return this.CityField;
            }
            set {
                if ((object.ReferenceEquals(this.CityField, value) != true)) {
                    this.CityField = value;
                    this.RaisePropertyChanged("City");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Wellness.EmployeeService.Club Club {
            get {
                return this.ClubField;
            }
            set {
                if ((object.ReferenceEquals(this.ClubField, value) != true)) {
                    this.ClubField = value;
                    this.RaisePropertyChanged("Club");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Wellness.EmployeeService.Club[] ClubAccess {
            get {
                return this.ClubAccessField;
            }
            set {
                if ((object.ReferenceEquals(this.ClubAccessField, value) != true)) {
                    this.ClubAccessField = value;
                    this.RaisePropertyChanged("ClubAccess");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> DateOfBirth {
            get {
                return this.DateOfBirthField;
            }
            set {
                if ((this.DateOfBirthField.Equals(value) != true)) {
                    this.DateOfBirthField = value;
                    this.RaisePropertyChanged("DateOfBirth");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EmergencyContact {
            get {
                return this.EmergencyContactField;
            }
            set {
                if ((object.ReferenceEquals(this.EmergencyContactField, value) != true)) {
                    this.EmergencyContactField = value;
                    this.RaisePropertyChanged("EmergencyContact");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EmergencyPhone {
            get {
                return this.EmergencyPhoneField;
            }
            set {
                if ((object.ReferenceEquals(this.EmergencyPhoneField, value) != true)) {
                    this.EmergencyPhoneField = value;
                    this.RaisePropertyChanged("EmergencyPhone");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FirstName {
            get {
                return this.FirstNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FirstNameField, value) != true)) {
                    this.FirstNameField = value;
                    this.RaisePropertyChanged("FirstName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string HomePhone {
            get {
                return this.HomePhoneField;
            }
            set {
                if ((object.ReferenceEquals(this.HomePhoneField, value) != true)) {
                    this.HomePhoneField = value;
                    this.RaisePropertyChanged("HomePhone");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Wellness.EmployeeService.ClubGroup[] InstructorSearchClubGroups {
            get {
                return this.InstructorSearchClubGroupsField;
            }
            set {
                if ((object.ReferenceEquals(this.InstructorSearchClubGroupsField, value) != true)) {
                    this.InstructorSearchClubGroupsField = value;
                    this.RaisePropertyChanged("InstructorSearchClubGroups");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Wellness.EmployeeService.Club[] InstructorSearchClubs {
            get {
                return this.InstructorSearchClubsField;
            }
            set {
                if ((object.ReferenceEquals(this.InstructorSearchClubsField, value) != true)) {
                    this.InstructorSearchClubsField = value;
                    this.RaisePropertyChanged("InstructorSearchClubs");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LastName {
            get {
                return this.LastNameField;
            }
            set {
                if ((object.ReferenceEquals(this.LastNameField, value) != true)) {
                    this.LastNameField = value;
                    this.RaisePropertyChanged("LastName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MiddleInitial {
            get {
                return this.MiddleInitialField;
            }
            set {
                if ((object.ReferenceEquals(this.MiddleInitialField, value) != true)) {
                    this.MiddleInitialField = value;
                    this.RaisePropertyChanged("MiddleInitial");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MobilePhone {
            get {
                return this.MobilePhoneField;
            }
            set {
                if ((object.ReferenceEquals(this.MobilePhoneField, value) != true)) {
                    this.MobilePhoneField = value;
                    this.RaisePropertyChanged("MobilePhone");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PreferredName {
            get {
                return this.PreferredNameField;
            }
            set {
                if ((object.ReferenceEquals(this.PreferredNameField, value) != true)) {
                    this.PreferredNameField = value;
                    this.RaisePropertyChanged("PreferredName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string State {
            get {
                return this.StateField;
            }
            set {
                if ((object.ReferenceEquals(this.StateField, value) != true)) {
                    this.StateField = value;
                    this.RaisePropertyChanged("State");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ZipCode {
            get {
                return this.ZipCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.ZipCodeField, value) != true)) {
                    this.ZipCodeField = value;
                    this.RaisePropertyChanged("ZipCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=21)]
        public string Password {
            get {
                return this.PasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswordField, value) != true)) {
                    this.PasswordField = value;
                    this.RaisePropertyChanged("Password");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EmployeeUpdate", Namespace="http://JonasFitness.com/CompeteDataService/v2_0/Common")]
    [System.SerializableAttribute()]
    public partial class EmployeeUpdate : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<bool> ActiveField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Address1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Address2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BarcodeIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Wellness.EmployeeService.Club ClubField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Wellness.EmployeeService.Club[] ClubAccessField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> DateOfBirthField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmergencyContactField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmergencyPhoneField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FirstNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string HomePhoneField;
        
        private int IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Wellness.EmployeeService.ClubGroup[] InstructorSearchClubGroupsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Wellness.EmployeeService.Club[] InstructorSearchClubsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LastNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MiddleInitialField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MobilePhoneField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PreferredNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ZipCodeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> Active {
            get {
                return this.ActiveField;
            }
            set {
                if ((this.ActiveField.Equals(value) != true)) {
                    this.ActiveField = value;
                    this.RaisePropertyChanged("Active");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Address1 {
            get {
                return this.Address1Field;
            }
            set {
                if ((object.ReferenceEquals(this.Address1Field, value) != true)) {
                    this.Address1Field = value;
                    this.RaisePropertyChanged("Address1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Address2 {
            get {
                return this.Address2Field;
            }
            set {
                if ((object.ReferenceEquals(this.Address2Field, value) != true)) {
                    this.Address2Field = value;
                    this.RaisePropertyChanged("Address2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BarcodeID {
            get {
                return this.BarcodeIDField;
            }
            set {
                if ((object.ReferenceEquals(this.BarcodeIDField, value) != true)) {
                    this.BarcodeIDField = value;
                    this.RaisePropertyChanged("BarcodeID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string City {
            get {
                return this.CityField;
            }
            set {
                if ((object.ReferenceEquals(this.CityField, value) != true)) {
                    this.CityField = value;
                    this.RaisePropertyChanged("City");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Wellness.EmployeeService.Club Club {
            get {
                return this.ClubField;
            }
            set {
                if ((object.ReferenceEquals(this.ClubField, value) != true)) {
                    this.ClubField = value;
                    this.RaisePropertyChanged("Club");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Wellness.EmployeeService.Club[] ClubAccess {
            get {
                return this.ClubAccessField;
            }
            set {
                if ((object.ReferenceEquals(this.ClubAccessField, value) != true)) {
                    this.ClubAccessField = value;
                    this.RaisePropertyChanged("ClubAccess");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> DateOfBirth {
            get {
                return this.DateOfBirthField;
            }
            set {
                if ((this.DateOfBirthField.Equals(value) != true)) {
                    this.DateOfBirthField = value;
                    this.RaisePropertyChanged("DateOfBirth");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EmergencyContact {
            get {
                return this.EmergencyContactField;
            }
            set {
                if ((object.ReferenceEquals(this.EmergencyContactField, value) != true)) {
                    this.EmergencyContactField = value;
                    this.RaisePropertyChanged("EmergencyContact");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EmergencyPhone {
            get {
                return this.EmergencyPhoneField;
            }
            set {
                if ((object.ReferenceEquals(this.EmergencyPhoneField, value) != true)) {
                    this.EmergencyPhoneField = value;
                    this.RaisePropertyChanged("EmergencyPhone");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FirstName {
            get {
                return this.FirstNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FirstNameField, value) != true)) {
                    this.FirstNameField = value;
                    this.RaisePropertyChanged("FirstName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string HomePhone {
            get {
                return this.HomePhoneField;
            }
            set {
                if ((object.ReferenceEquals(this.HomePhoneField, value) != true)) {
                    this.HomePhoneField = value;
                    this.RaisePropertyChanged("HomePhone");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Wellness.EmployeeService.ClubGroup[] InstructorSearchClubGroups {
            get {
                return this.InstructorSearchClubGroupsField;
            }
            set {
                if ((object.ReferenceEquals(this.InstructorSearchClubGroupsField, value) != true)) {
                    this.InstructorSearchClubGroupsField = value;
                    this.RaisePropertyChanged("InstructorSearchClubGroups");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Wellness.EmployeeService.Club[] InstructorSearchClubs {
            get {
                return this.InstructorSearchClubsField;
            }
            set {
                if ((object.ReferenceEquals(this.InstructorSearchClubsField, value) != true)) {
                    this.InstructorSearchClubsField = value;
                    this.RaisePropertyChanged("InstructorSearchClubs");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LastName {
            get {
                return this.LastNameField;
            }
            set {
                if ((object.ReferenceEquals(this.LastNameField, value) != true)) {
                    this.LastNameField = value;
                    this.RaisePropertyChanged("LastName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MiddleInitial {
            get {
                return this.MiddleInitialField;
            }
            set {
                if ((object.ReferenceEquals(this.MiddleInitialField, value) != true)) {
                    this.MiddleInitialField = value;
                    this.RaisePropertyChanged("MiddleInitial");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MobilePhone {
            get {
                return this.MobilePhoneField;
            }
            set {
                if ((object.ReferenceEquals(this.MobilePhoneField, value) != true)) {
                    this.MobilePhoneField = value;
                    this.RaisePropertyChanged("MobilePhone");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PreferredName {
            get {
                return this.PreferredNameField;
            }
            set {
                if ((object.ReferenceEquals(this.PreferredNameField, value) != true)) {
                    this.PreferredNameField = value;
                    this.RaisePropertyChanged("PreferredName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string State {
            get {
                return this.StateField;
            }
            set {
                if ((object.ReferenceEquals(this.StateField, value) != true)) {
                    this.StateField = value;
                    this.RaisePropertyChanged("State");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ZipCode {
            get {
                return this.ZipCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.ZipCodeField, value) != true)) {
                    this.ZipCodeField = value;
                    this.RaisePropertyChanged("ZipCode");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="StatusInfo", Namespace="http://JonasFitness.com/CompeteDataService/v2_0/Responses")]
    [System.SerializableAttribute()]
    public partial class StatusInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private Wellness.EmployeeService.StatusCode StatusField;
        
        private string MessageField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public Wellness.EmployeeService.StatusCode Status {
            get {
                return this.StatusField;
            }
            set {
                if ((this.StatusField.Equals(value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ErrorStatusInfo", Namespace="http://JonasFitness.com/CompeteDataService/v2_0/Responses")]
    [System.SerializableAttribute()]
    public partial class ErrorStatusInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private Wellness.EmployeeService.StatusCode StatusField;
        
        private string MessageField;
        
        private int ErrorNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RequestEchoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public Wellness.EmployeeService.StatusCode Status {
            get {
                return this.StatusField;
            }
            set {
                if ((this.StatusField.Equals(value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public int ErrorNumber {
            get {
                return this.ErrorNumberField;
            }
            set {
                if ((this.ErrorNumberField.Equals(value) != true)) {
                    this.ErrorNumberField = value;
                    this.RaisePropertyChanged("ErrorNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public string RequestEcho {
            get {
                return this.RequestEchoField;
            }
            set {
                if ((object.ReferenceEquals(this.RequestEchoField, value) != true)) {
                    this.RequestEchoField = value;
                    this.RaisePropertyChanged("RequestEcho");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PagedResponseInfo", Namespace="http://JonasFitness.com/CompeteDataService/v2_0/Responses")]
    [System.SerializableAttribute()]
    public partial class PagedResponseInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int PageField;
        
        private int PageSizeField;
        
        private int TotalPagesField;
        
        private int TotalRecordsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Page {
            get {
                return this.PageField;
            }
            set {
                if ((this.PageField.Equals(value) != true)) {
                    this.PageField = value;
                    this.RaisePropertyChanged("Page");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int PageSize {
            get {
                return this.PageSizeField;
            }
            set {
                if ((this.PageSizeField.Equals(value) != true)) {
                    this.PageSizeField = value;
                    this.RaisePropertyChanged("PageSize");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int TotalPages {
            get {
                return this.TotalPagesField;
            }
            set {
                if ((this.TotalPagesField.Equals(value) != true)) {
                    this.TotalPagesField = value;
                    this.RaisePropertyChanged("TotalPages");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int TotalRecords {
            get {
                return this.TotalRecordsField;
            }
            set {
                if ((this.TotalRecordsField.Equals(value) != true)) {
                    this.TotalRecordsField = value;
                    this.RaisePropertyChanged("TotalRecords");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="StatusCode", Namespace="http://schemas.datacontract.org/2004/07/JonasFitness.ClubSolutions.CompeteDataSer" +
        "vice.ServiceConnector.DataContracts.Version2_0.Responses")]
    public enum StatusCode : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Success = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Warning = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SystemError = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        RequestError = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        AuthenticationError = 4,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://JonasFitness.com/CompeteDataService/v2_0/EmployeeService", ConfigurationName="EmployeeService.IEmployeeService")]
    public interface IEmployeeService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://JonasFitness.com/CompeteDataService/v2_0/EmployeeService/GetEmployees", ReplyAction="http://JonasFitness.com/CompeteDataService/v2_0/EmployeeService/IEmployeeService/" +
            "GetEmployeesResponse")]
        Wellness.EmployeeService.GetEmployeesResponse GetEmployees(Wellness.EmployeeService.GetEmployeesRequest GetEmployeesRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://JonasFitness.com/CompeteDataService/v2_0/EmployeeService/GetEmployees", ReplyAction="http://JonasFitness.com/CompeteDataService/v2_0/EmployeeService/IEmployeeService/" +
            "GetEmployeesResponse")]
        System.Threading.Tasks.Task<Wellness.EmployeeService.GetEmployeesResponse> GetEmployeesAsync(Wellness.EmployeeService.GetEmployeesRequest GetEmployeesRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://JonasFitness.com/CompeteDataService/v2_0/EmployeeService/InsertEmployees", ReplyAction="http://JonasFitness.com/CompeteDataService/v2_0/EmployeeService/IEmployeeService/" +
            "InsertEmployeesResponse")]
        Wellness.EmployeeService.InsertEmployeesResponse InsertEmployees(Wellness.EmployeeService.InsertEmployeesRequest InsertEmployeesRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://JonasFitness.com/CompeteDataService/v2_0/EmployeeService/InsertEmployees", ReplyAction="http://JonasFitness.com/CompeteDataService/v2_0/EmployeeService/IEmployeeService/" +
            "InsertEmployeesResponse")]
        System.Threading.Tasks.Task<Wellness.EmployeeService.InsertEmployeesResponse> InsertEmployeesAsync(Wellness.EmployeeService.InsertEmployeesRequest InsertEmployeesRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://JonasFitness.com/CompeteDataService/v2_0/EmployeeService/UpdateEmployees", ReplyAction="http://JonasFitness.com/CompeteDataService/v2_0/EmployeeService/IEmployeeService/" +
            "UpdateEmployeesResponse")]
        Wellness.EmployeeService.UpdateEmployeesResponse UpdateEmployees(Wellness.EmployeeService.UpdateEmployeesRequest UpdateEmployeesRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://JonasFitness.com/CompeteDataService/v2_0/EmployeeService/UpdateEmployees", ReplyAction="http://JonasFitness.com/CompeteDataService/v2_0/EmployeeService/IEmployeeService/" +
            "UpdateEmployeesResponse")]
        System.Threading.Tasks.Task<Wellness.EmployeeService.UpdateEmployeesResponse> UpdateEmployeesAsync(Wellness.EmployeeService.UpdateEmployeesRequest UpdateEmployeesRequest);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IEmployeeServiceChannel : Wellness.EmployeeService.IEmployeeService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class EmployeeServiceClient : System.ServiceModel.ClientBase<Wellness.EmployeeService.IEmployeeService>, Wellness.EmployeeService.IEmployeeService {
        
        public EmployeeServiceClient() {
        }
        
        public EmployeeServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public EmployeeServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EmployeeServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EmployeeServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Wellness.EmployeeService.GetEmployeesResponse GetEmployees(Wellness.EmployeeService.GetEmployeesRequest GetEmployeesRequest) {
            return base.Channel.GetEmployees(GetEmployeesRequest);
        }
        
        public System.Threading.Tasks.Task<Wellness.EmployeeService.GetEmployeesResponse> GetEmployeesAsync(Wellness.EmployeeService.GetEmployeesRequest GetEmployeesRequest) {
            return base.Channel.GetEmployeesAsync(GetEmployeesRequest);
        }
        
        public Wellness.EmployeeService.InsertEmployeesResponse InsertEmployees(Wellness.EmployeeService.InsertEmployeesRequest InsertEmployeesRequest) {
            return base.Channel.InsertEmployees(InsertEmployeesRequest);
        }
        
        public System.Threading.Tasks.Task<Wellness.EmployeeService.InsertEmployeesResponse> InsertEmployeesAsync(Wellness.EmployeeService.InsertEmployeesRequest InsertEmployeesRequest) {
            return base.Channel.InsertEmployeesAsync(InsertEmployeesRequest);
        }
        
        public Wellness.EmployeeService.UpdateEmployeesResponse UpdateEmployees(Wellness.EmployeeService.UpdateEmployeesRequest UpdateEmployeesRequest) {
            return base.Channel.UpdateEmployees(UpdateEmployeesRequest);
        }
        
        public System.Threading.Tasks.Task<Wellness.EmployeeService.UpdateEmployeesResponse> UpdateEmployeesAsync(Wellness.EmployeeService.UpdateEmployeesRequest UpdateEmployeesRequest) {
            return base.Channel.UpdateEmployeesAsync(UpdateEmployeesRequest);
        }
    }
}
