//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wellness.ClubService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Deserializer", Namespace="http://schemas.datacontract.org/2004/07/JonasFitness.ClubSolutions.CompeteDataSer" +
        "vice.ServiceConnector.DataContracts.Version2_0.Requests")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Wellness.ClubService.GetClubGroupsRequest))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Wellness.ClubService.GetClubsRequest))]
    public partial class Deserializer : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetClubGroupsRequest", Namespace="http://JonasFitness.com/CompeteDataService/v2_0/Requests")]
    [System.SerializableAttribute()]
    public partial class GetClubGroupsRequest : Wellness.ClubService.Deserializer {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Wellness.ClubService.ClubGroup[] ClubGroupsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Wellness.ClubService.PagingRequestInfo PageInfoField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Wellness.ClubService.ClubGroup[] ClubGroups {
            get {
                return this.ClubGroupsField;
            }
            set {
                if ((object.ReferenceEquals(this.ClubGroupsField, value) != true)) {
                    this.ClubGroupsField = value;
                    this.RaisePropertyChanged("ClubGroups");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Wellness.ClubService.PagingRequestInfo PageInfo {
            get {
                return this.PageInfoField;
            }
            set {
                if ((object.ReferenceEquals(this.PageInfoField, value) != true)) {
                    this.PageInfoField = value;
                    this.RaisePropertyChanged("PageInfo");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetClubsRequest", Namespace="http://JonasFitness.com/CompeteDataService/v2_0/Requests")]
    [System.SerializableAttribute()]
    public partial class GetClubsRequest : Wellness.ClubService.Deserializer {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Wellness.ClubService.Club[] ClubsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Wellness.ClubService.PagingRequestInfo PageInfoField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Wellness.ClubService.Club[] Clubs {
            get {
                return this.ClubsField;
            }
            set {
                if ((object.ReferenceEquals(this.ClubsField, value) != true)) {
                    this.ClubsField = value;
                    this.RaisePropertyChanged("Clubs");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Wellness.ClubService.PagingRequestInfo PageInfo {
            get {
                return this.PageInfoField;
            }
            set {
                if ((object.ReferenceEquals(this.PageInfoField, value) != true)) {
                    this.PageInfoField = value;
                    this.RaisePropertyChanged("PageInfo");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PagingRequestInfo", Namespace="http://JonasFitness.com/CompeteDataService/v2_0/Requests")]
    [System.SerializableAttribute()]
    public partial class PagingRequestInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PageSizeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Page {
            get {
                return this.PageField;
            }
            set {
                if ((this.PageField.Equals(value) != true)) {
                    this.PageField = value;
                    this.RaisePropertyChanged("Page");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PageSize {
            get {
                return this.PageSizeField;
            }
            set {
                if ((this.PageSizeField.Equals(value) != true)) {
                    this.PageSizeField = value;
                    this.RaisePropertyChanged("PageSize");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Club", Namespace="http://JonasFitness.com/CompeteDataService/v2_0/Common")]
    [System.SerializableAttribute()]
    public partial class Club : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int IDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ClubGroup", Namespace="http://JonasFitness.com/CompeteDataService/v2_0/Common")]
    [System.SerializableAttribute()]
    public partial class ClubGroup : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int IDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResponseRoot", Namespace="http://JonasFitness.com/CompeteDataService/v2_0/Responses")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Wellness.ClubService.GetClubGroupsResponse))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Wellness.ClubService.InsertClubGroupsResponse))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Wellness.ClubService.InsertClubGroupResult))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Wellness.ClubService.UpdateClubGroupsResponse))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Wellness.ClubService.UpdateClubGroupResult))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Wellness.ClubService.GetClubsResponse))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Wellness.ClubService.GetClubsRequest))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Wellness.ClubService.PagingRequestInfo))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Wellness.ClubService.GetClubGroupsRequest))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Wellness.ClubService.InsertClubGroupsRequest))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Wellness.ClubService.ClubGroupInsert[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Wellness.ClubService.ClubGroupInsert))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Wellness.ClubService.UpdateClubGroupsRequest))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Wellness.ClubService.ClubGroupUpdate[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Wellness.ClubService.ClubGroupUpdate))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Wellness.ClubService.Deserializer))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Wellness.ClubService.Club[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Wellness.ClubService.Club))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Wellness.ClubService.DetailedClub[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Wellness.ClubService.DetailedClub))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Wellness.ClubService.ClubGroup[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Wellness.ClubService.ClubGroup))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Wellness.ClubService.StatusInfo))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Wellness.ClubService.ErrorStatusInfo))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Wellness.ClubService.PagedResponseInfo))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Wellness.ClubService.InsertClubGroupResult[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Wellness.ClubService.UpdateClubGroupResult[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Wellness.ClubService.StatusCode))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Wellness.ClubService.ExpandedClubGroup[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Wellness.ClubService.ExpandedClubGroup))]
    public partial class ResponseRoot : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private object StatusInfoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public object StatusInfo {
            get {
                return this.StatusInfoField;
            }
            set {
                if ((object.ReferenceEquals(this.StatusInfoField, value) != true)) {
                    this.StatusInfoField = value;
                    this.RaisePropertyChanged("StatusInfo");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetClubGroupsResponse", Namespace="http://JonasFitness.com/CompeteDataService/v2_0/Responses")]
    [System.SerializableAttribute()]
    public partial class GetClubGroupsResponse : Wellness.ClubService.ResponseRoot {
        
        private Wellness.ClubService.ExpandedClubGroup[] ClubGroupsField;
        
        private Wellness.ClubService.PagedResponseInfo PageInfoField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public Wellness.ClubService.ExpandedClubGroup[] ClubGroups {
            get {
                return this.ClubGroupsField;
            }
            set {
                if ((object.ReferenceEquals(this.ClubGroupsField, value) != true)) {
                    this.ClubGroupsField = value;
                    this.RaisePropertyChanged("ClubGroups");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public Wellness.ClubService.PagedResponseInfo PageInfo {
            get {
                return this.PageInfoField;
            }
            set {
                if ((object.ReferenceEquals(this.PageInfoField, value) != true)) {
                    this.PageInfoField = value;
                    this.RaisePropertyChanged("PageInfo");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="InsertClubGroupsResponse", Namespace="http://JonasFitness.com/CompeteDataService/v2_0/Responses")]
    [System.SerializableAttribute()]
    public partial class InsertClubGroupsResponse : Wellness.ClubService.ResponseRoot {
        
        private Wellness.ClubService.InsertClubGroupResult[] ResultsField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public Wellness.ClubService.InsertClubGroupResult[] Results {
            get {
                return this.ResultsField;
            }
            set {
                if ((object.ReferenceEquals(this.ResultsField, value) != true)) {
                    this.ResultsField = value;
                    this.RaisePropertyChanged("Results");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="InsertClubGroupResult", Namespace="http://JonasFitness.com/CompeteDataService/v2_0/Responses")]
    [System.SerializableAttribute()]
    public partial class InsertClubGroupResult : Wellness.ClubService.ResponseRoot {
        
        private string ClubGroupNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int NewClubGroupIDField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string ClubGroupName {
            get {
                return this.ClubGroupNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ClubGroupNameField, value) != true)) {
                    this.ClubGroupNameField = value;
                    this.RaisePropertyChanged("ClubGroupName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int NewClubGroupID {
            get {
                return this.NewClubGroupIDField;
            }
            set {
                if ((this.NewClubGroupIDField.Equals(value) != true)) {
                    this.NewClubGroupIDField = value;
                    this.RaisePropertyChanged("NewClubGroupID");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UpdateClubGroupsResponse", Namespace="http://JonasFitness.com/CompeteDataService/v2_0/Responses")]
    [System.SerializableAttribute()]
    public partial class UpdateClubGroupsResponse : Wellness.ClubService.ResponseRoot {
        
        private Wellness.ClubService.UpdateClubGroupResult[] ResultsField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public Wellness.ClubService.UpdateClubGroupResult[] Results {
            get {
                return this.ResultsField;
            }
            set {
                if ((object.ReferenceEquals(this.ResultsField, value) != true)) {
                    this.ResultsField = value;
                    this.RaisePropertyChanged("Results");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UpdateClubGroupResult", Namespace="http://JonasFitness.com/CompeteDataService/v2_0/Responses")]
    [System.SerializableAttribute()]
    public partial class UpdateClubGroupResult : Wellness.ClubService.ResponseRoot {
        
        private int ClubGroupIDField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int ClubGroupID {
            get {
                return this.ClubGroupIDField;
            }
            set {
                if ((this.ClubGroupIDField.Equals(value) != true)) {
                    this.ClubGroupIDField = value;
                    this.RaisePropertyChanged("ClubGroupID");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetClubsResponse", Namespace="http://JonasFitness.com/CompeteDataService/v2_0/Responses")]
    [System.SerializableAttribute()]
    public partial class GetClubsResponse : Wellness.ClubService.ResponseRoot {
        
        private Wellness.ClubService.DetailedClub[] ClubsField;
        
        private Wellness.ClubService.PagedResponseInfo PageInfoField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public Wellness.ClubService.DetailedClub[] Clubs {
            get {
                return this.ClubsField;
            }
            set {
                if ((object.ReferenceEquals(this.ClubsField, value) != true)) {
                    this.ClubsField = value;
                    this.RaisePropertyChanged("Clubs");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public Wellness.ClubService.PagedResponseInfo PageInfo {
            get {
                return this.PageInfoField;
            }
            set {
                if ((object.ReferenceEquals(this.PageInfoField, value) != true)) {
                    this.PageInfoField = value;
                    this.RaisePropertyChanged("PageInfo");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="InsertClubGroupsRequest", Namespace="http://JonasFitness.com/CompeteDataService/v2_0/Requests")]
    [System.SerializableAttribute()]
    public partial class InsertClubGroupsRequest : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private Wellness.ClubService.ClubGroupInsert[] InsertsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public Wellness.ClubService.ClubGroupInsert[] Inserts {
            get {
                return this.InsertsField;
            }
            set {
                if ((object.ReferenceEquals(this.InsertsField, value) != true)) {
                    this.InsertsField = value;
                    this.RaisePropertyChanged("Inserts");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ClubGroupInsert", Namespace="http://JonasFitness.com/CompeteDataService/v2_0/Requests")]
    [System.SerializableAttribute()]
    public partial class ClubGroupInsert : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Wellness.ClubService.Club[] ClubsField;
        
        private string NameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Wellness.ClubService.Club[] Clubs {
            get {
                return this.ClubsField;
            }
            set {
                if ((object.ReferenceEquals(this.ClubsField, value) != true)) {
                    this.ClubsField = value;
                    this.RaisePropertyChanged("Clubs");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UpdateClubGroupsRequest", Namespace="http://JonasFitness.com/CompeteDataService/v2_0/Requests")]
    [System.SerializableAttribute()]
    public partial class UpdateClubGroupsRequest : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private Wellness.ClubService.ClubGroupUpdate[] UpdatesField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public Wellness.ClubService.ClubGroupUpdate[] Updates {
            get {
                return this.UpdatesField;
            }
            set {
                if ((object.ReferenceEquals(this.UpdatesField, value) != true)) {
                    this.UpdatesField = value;
                    this.RaisePropertyChanged("Updates");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ClubGroupUpdate", Namespace="http://JonasFitness.com/CompeteDataService/v2_0/Requests")]
    [System.SerializableAttribute()]
    public partial class ClubGroupUpdate : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Wellness.ClubService.Club[] ClubsToAddField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Wellness.ClubService.Club[] ClubsToRemoveField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public Wellness.ClubService.Club[] ClubsToAdd {
            get {
                return this.ClubsToAddField;
            }
            set {
                if ((object.ReferenceEquals(this.ClubsToAddField, value) != true)) {
                    this.ClubsToAddField = value;
                    this.RaisePropertyChanged("ClubsToAdd");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public Wellness.ClubService.Club[] ClubsToRemove {
            get {
                return this.ClubsToRemoveField;
            }
            set {
                if ((object.ReferenceEquals(this.ClubsToRemoveField, value) != true)) {
                    this.ClubsToRemoveField = value;
                    this.RaisePropertyChanged("ClubsToRemove");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DetailedClub", Namespace="http://JonasFitness.com/CompeteDataService/v2_0/Common")]
    [System.SerializableAttribute()]
    public partial class DetailedClub : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Address1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Address2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Wellness.ClubService.ClubGroup[] ClubGroupsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PhoneField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ZipcodeField;
        
        private int IDField;
        
        private string NameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Address1 {
            get {
                return this.Address1Field;
            }
            set {
                if ((object.ReferenceEquals(this.Address1Field, value) != true)) {
                    this.Address1Field = value;
                    this.RaisePropertyChanged("Address1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Address2 {
            get {
                return this.Address2Field;
            }
            set {
                if ((object.ReferenceEquals(this.Address2Field, value) != true)) {
                    this.Address2Field = value;
                    this.RaisePropertyChanged("Address2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string City {
            get {
                return this.CityField;
            }
            set {
                if ((object.ReferenceEquals(this.CityField, value) != true)) {
                    this.CityField = value;
                    this.RaisePropertyChanged("City");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Wellness.ClubService.ClubGroup[] ClubGroups {
            get {
                return this.ClubGroupsField;
            }
            set {
                if ((object.ReferenceEquals(this.ClubGroupsField, value) != true)) {
                    this.ClubGroupsField = value;
                    this.RaisePropertyChanged("ClubGroups");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Phone {
            get {
                return this.PhoneField;
            }
            set {
                if ((object.ReferenceEquals(this.PhoneField, value) != true)) {
                    this.PhoneField = value;
                    this.RaisePropertyChanged("Phone");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string State {
            get {
                return this.StateField;
            }
            set {
                if ((object.ReferenceEquals(this.StateField, value) != true)) {
                    this.StateField = value;
                    this.RaisePropertyChanged("State");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Zipcode {
            get {
                return this.ZipcodeField;
            }
            set {
                if ((object.ReferenceEquals(this.ZipcodeField, value) != true)) {
                    this.ZipcodeField = value;
                    this.RaisePropertyChanged("Zipcode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=7)]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=8)]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="StatusInfo", Namespace="http://JonasFitness.com/CompeteDataService/v2_0/Responses")]
    [System.SerializableAttribute()]
    public partial class StatusInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private Wellness.ClubService.StatusCode StatusField;
        
        private string MessageField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public Wellness.ClubService.StatusCode Status {
            get {
                return this.StatusField;
            }
            set {
                if ((this.StatusField.Equals(value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ErrorStatusInfo", Namespace="http://JonasFitness.com/CompeteDataService/v2_0/Responses")]
    [System.SerializableAttribute()]
    public partial class ErrorStatusInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private Wellness.ClubService.StatusCode StatusField;
        
        private string MessageField;
        
        private int ErrorNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RequestEchoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public Wellness.ClubService.StatusCode Status {
            get {
                return this.StatusField;
            }
            set {
                if ((this.StatusField.Equals(value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public int ErrorNumber {
            get {
                return this.ErrorNumberField;
            }
            set {
                if ((this.ErrorNumberField.Equals(value) != true)) {
                    this.ErrorNumberField = value;
                    this.RaisePropertyChanged("ErrorNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public string RequestEcho {
            get {
                return this.RequestEchoField;
            }
            set {
                if ((object.ReferenceEquals(this.RequestEchoField, value) != true)) {
                    this.RequestEchoField = value;
                    this.RaisePropertyChanged("RequestEcho");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PagedResponseInfo", Namespace="http://JonasFitness.com/CompeteDataService/v2_0/Responses")]
    [System.SerializableAttribute()]
    public partial class PagedResponseInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int PageField;
        
        private int PageSizeField;
        
        private int TotalPagesField;
        
        private int TotalRecordsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Page {
            get {
                return this.PageField;
            }
            set {
                if ((this.PageField.Equals(value) != true)) {
                    this.PageField = value;
                    this.RaisePropertyChanged("Page");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int PageSize {
            get {
                return this.PageSizeField;
            }
            set {
                if ((this.PageSizeField.Equals(value) != true)) {
                    this.PageSizeField = value;
                    this.RaisePropertyChanged("PageSize");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int TotalPages {
            get {
                return this.TotalPagesField;
            }
            set {
                if ((this.TotalPagesField.Equals(value) != true)) {
                    this.TotalPagesField = value;
                    this.RaisePropertyChanged("TotalPages");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int TotalRecords {
            get {
                return this.TotalRecordsField;
            }
            set {
                if ((this.TotalRecordsField.Equals(value) != true)) {
                    this.TotalRecordsField = value;
                    this.RaisePropertyChanged("TotalRecords");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="StatusCode", Namespace="http://schemas.datacontract.org/2004/07/JonasFitness.ClubSolutions.CompeteDataSer" +
        "vice.ServiceConnector.DataContracts.Version2_0.Responses")]
    public enum StatusCode : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Success = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Warning = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SystemError = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        RequestError = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        AuthenticationError = 4,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ExpandedClubGroup", Namespace="http://schemas.datacontract.org/2004/07/JonasFitness.ClubSolutions.CompeteDataSer" +
        "vice.ServiceConnector.DataContracts.Version2_0.Common")]
    [System.SerializableAttribute()]
    public partial class ExpandedClubGroup : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Wellness.ClubService.Club[] ClubsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Wellness.ClubService.Club[] Clubs {
            get {
                return this.ClubsField;
            }
            set {
                if ((object.ReferenceEquals(this.ClubsField, value) != true)) {
                    this.ClubsField = value;
                    this.RaisePropertyChanged("Clubs");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://JonasFitness.com/CompeteDataService/v2_0/ClubService", ConfigurationName="ClubService.IClubService")]
    public interface IClubService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://JonasFitness.com/CompeteDataService/v2_0/ClubService/GetClubs", ReplyAction="http://JonasFitness.com/CompeteDataService/v2_0/ClubService/IClubService/GetClubs" +
            "Response")]
        Wellness.ClubService.GetClubsResponse GetClubs(Wellness.ClubService.GetClubsRequest GetClubsRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://JonasFitness.com/CompeteDataService/v2_0/ClubService/GetClubs", ReplyAction="http://JonasFitness.com/CompeteDataService/v2_0/ClubService/IClubService/GetClubs" +
            "Response")]
        System.Threading.Tasks.Task<Wellness.ClubService.GetClubsResponse> GetClubsAsync(Wellness.ClubService.GetClubsRequest GetClubsRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://JonasFitness.com/CompeteDataService/v2_0/ClubService/GetClubGroups", ReplyAction="http://JonasFitness.com/CompeteDataService/v2_0/ClubService/IClubService/GetClubG" +
            "roupsResponse")]
        Wellness.ClubService.GetClubGroupsResponse GetClubGroups(Wellness.ClubService.GetClubGroupsRequest GetClubGroupsRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://JonasFitness.com/CompeteDataService/v2_0/ClubService/GetClubGroups", ReplyAction="http://JonasFitness.com/CompeteDataService/v2_0/ClubService/IClubService/GetClubG" +
            "roupsResponse")]
        System.Threading.Tasks.Task<Wellness.ClubService.GetClubGroupsResponse> GetClubGroupsAsync(Wellness.ClubService.GetClubGroupsRequest GetClubGroupsRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://JonasFitness.com/CompeteDataService/v2_0/ClubService/InsertClubGroups", ReplyAction="http://JonasFitness.com/CompeteDataService/v2_0/ClubService/IClubService/InsertCl" +
            "ubGroupsResponse")]
        Wellness.ClubService.InsertClubGroupsResponse InsertClubGroups(Wellness.ClubService.InsertClubGroupsRequest InsertClubGroupsRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://JonasFitness.com/CompeteDataService/v2_0/ClubService/InsertClubGroups", ReplyAction="http://JonasFitness.com/CompeteDataService/v2_0/ClubService/IClubService/InsertCl" +
            "ubGroupsResponse")]
        System.Threading.Tasks.Task<Wellness.ClubService.InsertClubGroupsResponse> InsertClubGroupsAsync(Wellness.ClubService.InsertClubGroupsRequest InsertClubGroupsRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://JonasFitness.com/CompeteDataService/v2_0/ClubService/UpdateClubGroups", ReplyAction="http://JonasFitness.com/CompeteDataService/v2_0/ClubService/IClubService/UpdateCl" +
            "ubGroupsResponse")]
        Wellness.ClubService.UpdateClubGroupsResponse UpdateClubGroups(Wellness.ClubService.UpdateClubGroupsRequest UpdateClubGroupsRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://JonasFitness.com/CompeteDataService/v2_0/ClubService/UpdateClubGroups", ReplyAction="http://JonasFitness.com/CompeteDataService/v2_0/ClubService/IClubService/UpdateCl" +
            "ubGroupsResponse")]
        System.Threading.Tasks.Task<Wellness.ClubService.UpdateClubGroupsResponse> UpdateClubGroupsAsync(Wellness.ClubService.UpdateClubGroupsRequest UpdateClubGroupsRequest);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IClubServiceChannel : Wellness.ClubService.IClubService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ClubServiceClient : System.ServiceModel.ClientBase<Wellness.ClubService.IClubService>, Wellness.ClubService.IClubService {
        
        public ClubServiceClient() {
        }
        
        public ClubServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ClubServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ClubServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ClubServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Wellness.ClubService.GetClubsResponse GetClubs(Wellness.ClubService.GetClubsRequest GetClubsRequest) {
            return base.Channel.GetClubs(GetClubsRequest);
        }
        
        public System.Threading.Tasks.Task<Wellness.ClubService.GetClubsResponse> GetClubsAsync(Wellness.ClubService.GetClubsRequest GetClubsRequest) {
            return base.Channel.GetClubsAsync(GetClubsRequest);
        }
        
        public Wellness.ClubService.GetClubGroupsResponse GetClubGroups(Wellness.ClubService.GetClubGroupsRequest GetClubGroupsRequest) {
            return base.Channel.GetClubGroups(GetClubGroupsRequest);
        }
        
        public System.Threading.Tasks.Task<Wellness.ClubService.GetClubGroupsResponse> GetClubGroupsAsync(Wellness.ClubService.GetClubGroupsRequest GetClubGroupsRequest) {
            return base.Channel.GetClubGroupsAsync(GetClubGroupsRequest);
        }
        
        public Wellness.ClubService.InsertClubGroupsResponse InsertClubGroups(Wellness.ClubService.InsertClubGroupsRequest InsertClubGroupsRequest) {
            return base.Channel.InsertClubGroups(InsertClubGroupsRequest);
        }
        
        public System.Threading.Tasks.Task<Wellness.ClubService.InsertClubGroupsResponse> InsertClubGroupsAsync(Wellness.ClubService.InsertClubGroupsRequest InsertClubGroupsRequest) {
            return base.Channel.InsertClubGroupsAsync(InsertClubGroupsRequest);
        }
        
        public Wellness.ClubService.UpdateClubGroupsResponse UpdateClubGroups(Wellness.ClubService.UpdateClubGroupsRequest UpdateClubGroupsRequest) {
            return base.Channel.UpdateClubGroups(UpdateClubGroupsRequest);
        }
        
        public System.Threading.Tasks.Task<Wellness.ClubService.UpdateClubGroupsResponse> UpdateClubGroupsAsync(Wellness.ClubService.UpdateClubGroupsRequest UpdateClubGroupsRequest) {
            return base.Channel.UpdateClubGroupsAsync(UpdateClubGroupsRequest);
        }
    }
}
